OAS 3.1 for JSON Schemas
readmeio/oas pull request #530
Opened 2021-10-29 20:34 UTC by Dashron

## 🧰 Changes

This is all the work necessary to support OAS 3.1 for JSON schemas.

pre OAS 3.1 your JSON schema could only be draft `04`. 3.1 your JSON schema can be anything, as determined by the `$schema` value in your schema, the value of `jsonSchemaDialect` or the default, draft `2020-12`.

These updates to the OAS library now ensure that the schemas you are working with always have the accurate `$schema` value, following the previously mentioned chain of priorities.

Along the way I converted the following to typescript
- operation
- get-parameters-as-json-schema

## 🧬 QA & Testing

- tests

2021-11-22 21:14 UTC, Dashron commented
There's some *really* ugly typing going on in here, but let's get the typescript conversion over before we do code cleanup. I gave code cleanup a shot and it was *really* problematic.

2021-12-02 03:02 UTC, erunion requested changes

2021-12-02 03:02 UTC, erunion commented on src/operation/get-response-as-json-schema.ts
> +    if (headers[key] && (headers[key] as OpenAPIV3.HeaderObject | OpenAPIV3_1.HeaderObject).schema) {
Might want to make a `HeaderObject` in `rmoas.types` that shortcuts having to repeat `OpenAPIV3.HeaderObject | OpenAPIV3_1.HeaderObject`.

2021-12-02 03:05 UTC, erunion commented
I also made a couple changes for minor things I found, you can see all my changes here: https://github.com/readmeio/oas/compare//58d150e746f52e9a25fdfa4d27424ebce94b412d...1841ce8?expand=1

* Pulled back some code docs that got deleted
* Moved `import type` declarations to the top of the files they're in so we're consistent
* Moved the `ResponseExamples` and `RequestBodyExamples` exports back to using the exports from `get-*-examples.ts` because they're already there. Also removed the `| false` declaration that got added because those arrays of examples will never have a falsy entry because we do `.filter(Boolean)` on it.

2021-12-02 21:24 UTC, Dashron commented on __tests__/operation.test.ts
> +    expect(operation['api']).toStrictEqual(petstore);
At one point `api` was private, and this bypasses typescript's public/private check. It looks like it's no longer private though so it works with dot notation.

2021-12-02 21:24 UTC, erunion commented on __tests__/operation.test.ts
> +    expect(operation['api']).toStrictEqual(petstore);
I think there's also a `getApi()` accessor on `Operation` if you want to use that instead.

2021-12-02 21:27 UTC, Dashron commented on src/lib/openapi-to-json-schema.ts
> +    schema.enum = [...Array.from(new Set(schema.enum))];
weird, that all came from fixing some typing issues, looks to still be fine typewise without it.

2021-12-02 21:48 UTC, Dashron commented on src/operation.ts
> +    const oasTags = Object.fromEntries(oasTagMap);
I don't remember specifically, but I'm sure it's typing related. Happy to mess around with restoring the old version tomorrow morning if you'd like.

2021-12-02 21:51 UTC, Dashron commented
Just pushed up fixes for everything. LMK what you think.

2021-12-06 17:03 UTC, erunion approved these changes

2021-12-06 17:04 UTC, merged