fix: pass required array into merge schema
readmeio/oas pull request #797
Opened 2023-09-20 21:09 UTC by darrenyong

| 🚥 Resolves RM-8014 |
| :------------------- |

## 🧰 Changes
Currently, when we merge schemas, we don't pass in the `required` array. This makes is so that when an OAS file like the following comes up, the `required` array is cast out and there aren't any required parameters.

<details>
<summary>Nium — allOf with top-level oneOf</summary>

``` json

{
  "openapi": "3.0.1",
  "info": {
    "contact": {
      "email": "experience@nium.com",
      "name": "NIUM Platform",
      "url": "https://www.nium.com"
    },
    "description": "NIUM Platform",
    "license": {
      "name": "Copyright (c) 2023 NIUM"
    },
    "title": "FX",
    "version": "1.0"
  },
  "servers": [
    {
      "url": "https://gateway.nium.com/n1"
    }
  ],
  "paths": {
    "/api/v1/client/{clientHashId}/quotes": {
      "post": {
        "tags": [
          "Quotes"
        ],
        "x-info": {
          "apiType": "external"
        },
        "summary": "Create Quote",
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/QuoteCreationResponse"
                },
                "examples": {
                  "With_Amount": {
                    "value": {
                      "id": "quote_6wBIHIRhPElAHfcgVaDFZs",
                      "quoteType": "balance_transfer",
                      "expiryTime": "2023-06-16 05:07:03",
                      "lockPeriod": "5_mins",
                      "markupRate": 0.0093611,
                      "createdTime": "2023-06-16 05:02:03",
                      "exchangeRate": 1.3373,
                      "sourceAmount": 100,
                      "netExchangeRate": 1.3279389,
                      "destinationAmount": 132.79,
                      "conversionSchedule": "immediate",
                      "sourceCurrencyCode\"": "USD",
                      "destinationCurrencyCode": "SGD",
                      "destinationMarkupAmount": 0.94
                    },
                    "summary": "With Amounts"
                  },
                  "With_ECB_Rate": {
                    "value": {
                      "id": "quote_6wBIHIRhPElAHfcgVaDFZs",
                      "quoteType": "balance_transfer",
                      "expiryTime": "2023-06-16 05:07:03",
                      "lockPeriod": "5_mins",
                      "markupRate": 0.0063973,
                      "createdTime": "2023-06-16 05:02:03",
                      "exchangeRate": 0.9139,
                      "sourceAmount": 100,
                      "ecbExchangeRate": 0.9139,
                      "netExchangeRate": 0.9075027,
                      "destinationAmount": 90.75,
                      "conversionSchedule": "immediate",
                      "sourceCurrencyCode\"": "EUR",
                      "destinationCurrencyCode": "SGD",
                      "destinationMarkupAmount": 0.64
                    },
                    "summary": "With ECB Rate"
                  },
                  "With_No_Amount": {
                    "value": {
                      "id": "quote_6wBIHIRhPElAHfcgVaDFZs",
                      "quoteType": "balance_transfer",
                      "expiryTime": "2023-06-16 05:07:03",
                      "lockPeriod": "5_mins",
                      "markupRate": 0.0093611,
                      "createdTime": "2023-06-16 05:02:03",
                      "exchangeRate": 1.3373,
                      "sourceAmount": null,
                      "netExchangeRate": 1.3279389,
                      "destinationAmount": null,
                      "conversionSchedule": "immediate",
                      "sourceCurrencyCode\"": "USD",
                      "destinationCurrencyCode": "SGD",
                      "destinationMarkupAmount": null
                    },
                    "summary": "With No Amount"
                  }
                }
              }
            },
            "description": "OK"
          },
          "400": {
            "$ref": "#/components/responses/BadRequest"
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/Forbidden"
          },
          "404": {
            "$ref": "#/components/responses/NotFound"
          },
          "500": {
            "$ref": "#/components/responses/InternalError"
          }
        },
        "deprecated": false,
        "parameters": [
          {
            "$ref": "#/components/parameters/Authorization"
          },
          {
            "$ref": "#/components/parameters/CsrfToken"
          },
          {
            "$ref": "#/components/parameters/ClientHashId"
          },
          {
            "description": "Enter a unique UUID value",
            "in": "header",
            "name": "x-request-id",
            "schema": {
              "type": "string",
              "example": "{{$guid}}"
            }
          }
        ],
        "description": "This API creates an FX quote for a currency pair according to the desired lock period and conversion schedule. The FX rate provided by this API includes the Nium markup and can be utilized for any FX conversion within the quote's validity period.",
        "operationId": "createQuote",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/QuoteCreationRequest"
              }
            }
          },
          "required": true,
          "description": "quoteCreationRequest"
        },
        "security": [
          {
            "default": []
          }
        ],
        "x-auth-type": "Application & Application User",
        "x-throttling-tier": "Unlimited",
        "x-codegen-request-body-name": "QuoteCreationRequest",
        "x-wso2-application-security": {
          "optional": false,
          "security-types": [
            "api_key"
          ]
        }
      }
    }
  },
  "components": {
    "schemas": {
      "DCC": {
        "type": "string",
        "example": "SGD",
        "maxLength": 3,
        "minLength": 3,
        "description": "3-letter [ISO-4217 currency code](https://www.iso.org/iso-4217-currency-codes.html) for the destination amount."
      },
      "SCC": {
        "type": "string",
        "example": "USD",
        "maxLength": 3,
        "minLength": 3,
        "description": "3-letter [ISO-4217 currency code](https://www.iso.org/iso-4217-currency-codes.html) for the source amount.",
        "required": [
          "sourceCurrencyCode"
        ]
      },
      "QuoteId": {
        "type": "string",
        "example": "quote_1234567890abcdefABCDEF",
        "description": "Unique identifier of the quote."
      },
      "QuoteType": {
        "enum": [
          "balance_transfer",
          "payout"
        ],
        "type": "string",
        "title": "QuoteType",
        "description": "The type of the quote."
      },
      "LockPeriod": {
        "enum": [
          "5_mins",
          "15_mins",
          "1_hour",
          "4_hours",
          "8_hours",
          "24_hours"
        ],
        "type": "string",
        "title": "LockPeriod",
        "default": "5_mins",
        "example": "15_mins",
        "description": "The time period for which the quote is locked."
      },
      "MarkupRate": {
        "type": "number",
        "format": "double",
        "example": 0.006745677,
        "description": "Markup rate applied by Nium."
      },
      "CreatedTime": {
        "type": "string",
        "format": "date-time",
        "example": "2021-03-09T06:46:03Z",
        "description": "Time of creation in UTC."
      },
      "ExchangeRate": {
        "type": "number",
        "format": "double",
        "example": 1.349324513,
        "description": "Foreign exchange market rate for the currency pair, used as the be [...]

2023-09-20 22:01 UTC, kanadgupta approved these changes
100+ lines of test changes, a single line fix... love PRs like these 🫶🏽

2023-09-21 17:32 UTC, darrenyong commented
@kanadgupta 
noticed I was getting the following linter error on one of my tests 
> Property 'required' does not exist on type 'boolean

so switched it to use `.toHaveProperty` instead of `.toBeTruthy`. it's a more explicit test too since I laid out exactly what the `required` array should contain rather than it just existing!

2023-09-22 18:32 UTC, kanadgupta requested changes

2023-09-22 18:32 UTC, kanadgupta commented on __tests__/operation/get-parameters-as-json-schema.test.ts
> +let polymorphism: Oas;
this file doesn't appear to be used, could we remove it?

2023-09-22 18:32 UTC, kanadgupta commented on __tests__/operation/__snapshots__/get-parameters-as-json-schema.test.ts.snap
i think the snapshot in these file is also no longer being used, could you remove it?

2023-09-22 20:31 UTC, kanadgupta approved these changes

2023-09-22 20:31 UTC, merged