feat: support examples from openapi 3.1
readmeio/oas pull request #864
Opened 2024-04-24 08:49 UTC by Mokto

## 🧰 Changes

This supports OpenAPI "examples" property. This will notably fix all issues with FastAPI generating documentation.

## 🧬 QA & Testing

I ran it on multiple documentations with success but I might have missed something. Let me know if I did.

2024-04-24 12:34 UTC, kanadgupta requested changes
Hi, thanks for your contribution! Could you add tests for this? They're located in this file: https://github.com/readmeio/oas/blob/ef3f5e8b128f0fdd11a484f25d6b03d3c05bdc64/packages/oas/test/samples/index.test.ts#L13

Let us know if you need a hand. Thanks!

2024-04-24 13:41 UTC, Mokto commented
Just added one. Let me know if you need anything else ;)

2024-04-24 17:15 UTC, kanadgupta approved these changes
Going to defer to @erunion for the final approval but LGTM — thanks again!

2024-04-29 15:22 UTC, erunion approved these changes

2024-04-29 15:22 UTC, merged